- name: Variables
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "15hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learing {{Course}} from trainer {{Trainer}}, Duration is {{Duration}}."